version: "3.7"

services:
  android:
    image: softsam/android-23:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    ports:
      - 5900:5900
      - 5555:5555
    networks:
      - android-net
networks:
  android-net:
    driver: overlay
    attachable: true