version: "3.8"

services:
  android:
    build:
      dockerfile: Dockerfile
      context: .
    image: shadash/android-emulator:latest
    restart: always
    privileged: true
    environment:
      - EMULATOR=android-19
    volumes:
    - /dev/video0:/dev/video0
    ports:
      - 5902:5900